### ISSUE TITLE
1.13.10 mockjax not working: Cannot set property 'logging' of undefined

### ISSUE THREAD

**Issue by Andrew-Max** [danielspaniel/ember-data-factory-guy#133]
All attempts to reference mockjax in test-helper throw errrors becuase mockjax and mockjaxSettings are not defined. Anyone else seen this?

import MockUpdateRequest from './mock-update-request';
import MockCreateRequest from './mock-create-request';
import MockGetRequest from './mock-get-request';

all seem to work though.

fails on line 13 of factory-guy-test-helper.js

**Comment by Andrew-Max** [comment]
fixed by copying and pasting code from fix mockjax import in master. any idea when that will filter into 1.13.10?

**Comment by marnen** [comment]
Having the same error. @Andrew-Max Why did you close this? The issue is not resolved.

**Comment by marnen** [comment]
Never mind. It is resolved. Installing 2.1.0 fixed it.
